### ISSUE TITLE
输入支持目标和投注金额后没反应

### ISSUE THREAD

**Issue by whatxy** [sophisticate9008/fight#1]
![image](https://user-images.githubusercontent.com/110091393/181683152-a33653d7-ba7c-4ea9-97dc-d5453012e959.png)
![image](https://user-images.githubusercontent.com/110091393/181683159-f0c9d468-3490-472c-9f21-2ae7ac929209.png)
后面就没反应了

**Comment by sophisticate9008** [comment]
可以的话 请更新一下
并且第一次启动会出现此类情况

**Comment by whatxy** [comment]
可以了，谢谢
