### ISSUE TITLE
被封概率疑似增加

### ISSUE THREAD

**Issue by RShock** [sophisticate9008/fight#10]
最近几天7点我都会被封，然后被封的页面提示和以前是不一样的，里面有一个示例图：
![_1262183912_Screenshot_2022-08-09-09-21-24-835_com tencent mobileqq_1660008084000_wifi_0 jpg](https://user-images.githubusercontent.com/11630758/183546644-50c2d376-3d88-4220-8301-d9d6e17444a1.jpg)
我觉得可能是投注 倍率之类的词太敏感了，不知道其他人被封概率如何呢？

**Comment by sophisticate9008** [comment]
你是发错了?

**Comment by RShock** [comment]
没啊，腾讯举例就是这个图
不过你要是没见过，证明没被封过，应该是我个人问题吧

**Comment by sophisticate9008** [comment]
> 吧

不，是我都没人我，我只写，根本不知道玩家啥情况

**Comment by sophisticate9008** [comment]
而且前天改成应援了

**Comment by sophisticate9008** [comment]
我不知道很多人应援时图片是什么吊样子

**Comment by sophisticate9008** [comment]
话说我的图片制作出来好像就这个列表的样子 英桀还是紫色
