### ISSUE TITLE
报一个奖金计算bug

### ISSUE THREAD

**Issue by nicewsc** [sophisticate9008/fight#16]
![image](https://user-images.githubusercontent.com/59506907/192427063-92ddc920-8176-46bb-acad-285c94fd74c4.png)
当设定下注金额为负数时，获胜会给金币数加一个计算后的数据（还是负数），使得金币数减少
反之，失败时会扣除一个计算后的数据（还是负数），使得金币数增加

**Comment by sophisticate9008** [comment]
牛
