### ISSUE TITLE
100%胜率战败

### ISSUE THREAD

**Issue by luvsagiri** [sophisticate9008/fight#2]
![QQ截图20220730130356](https://user-images.githubusercontent.com/55885527/181875608-4eced652-af8f-451d-a377-560530915f43.png)
![QQ截图20220730130350](https://user-images.githubusercontent.com/55885527/181875610-2f5bd240-f0fc-4934-ae68-731abc9c8b54.png)
![QQ截图20220730130326](https://user-images.githubusercontent.com/55885527/181875612-4936bc3c-da06-4390-9fb8-05a72a1f47b0.png)

**Comment by sophisticate9008** [comment]
科斯魔好像确实有问题
跟其他人对上也是0

**Comment by sophisticate9008** [comment]
伤害计算写到显示控制里了
计算概率的时候是不显示的
单次才显示
