### ISSUE TITLE
赔率与实际获得金币不符

### ISSUE THREAD

**Issue by wangyousama** [sophisticate9008/fight#3]
![9ZWPP@~%R417O{ {8_(0$FB](https://user-images.githubusercontent.com/107395159/181921092-32095296-d1c8-4ebc-b818-77b05d09d7f4.png)
![BD} N(E3 I3UGR7W2SCU$4B](https://user-images.githubusercontent.com/107395159/181921100-14138d88-4c87-4ae8-8a74-2979f27a6b0c.png)
![5V9C7 JII_3{IO$@RY_L~{I](https://user-images.githubusercontent.com/107395159/181921104-8d1fc972-0ead-4325-9f61-4cd379dd6ca2.png)

太离谱了

**Comment by sophisticate9008** [comment]
啊啊，我的锅，我两个倍率都填成第一个了

**Comment by sophisticate9008** [comment]
我太粗心了

**Comment by sophisticate9008** [comment]
你可以根据修改历史将“0”改为"1"
