### ISSUE TITLE
抽点问题

### ISSUE THREAD

**Issue by RShock** [sophisticate9008/fight#4]
直接从本金抽点不合适，尤其是100%胜率这种，必然亏钱，而且会引起玩家的困惑
推荐从盈利抽点甚至不抽点
据我估计，就算不抽甚至送点，不会运用凯利公式照样会在20min内输完，太狠了

**Comment by sophisticate9008** [comment]
好多学问

**Comment by sophisticate9008** [comment]
虽然改了，但是投10000也就多给500

**Comment by sophisticate9008** [comment]
但是积少成多
