### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by mzociha** [sophisticate9008/fight#5]
![image](https://user-images.githubusercontent.com/110342747/182031358-8b2e4eb2-6e88-408f-bb7d-9870c05bca3d.png)
建议在随机到英桀这里放一下英桀图片，就算我玩崩三也不一定能记得技能描述（脑子不好QAQ）

**Comment by sophisticate9008** [comment]
战斗记录里不是有么？

**Comment by sophisticate9008** [comment]
![Uploading Screenshot_2022-07-31-23-33-25-801_com.tencent.mobileqq.jpg…]()

**Comment by mozicha** [comment]
但是下注的时候不是没有嘛

**Comment by sophisticate9008** [comment]
胜率都告诉你了
而且我感觉现在发的消息够多了
![TQTML1CG~NX3F 5EO~ WKFG](https://user-images.githubusercontent.com/94435821/182056559-337f3c34-0ccf-41ee-a29a-59e26667e15b.jpg)
