### ISSUE TITLE
功能提议

### ISSUE THREAD

**Issue by 1294266616** [sophisticate9008/fight#7]
大大之后有计划多人下注不，感觉应该会很欢乐吧🤣

**Comment by sophisticate9008** [comment]
我试试

**Comment by 1294266616** [comment]
> 我试试

谢谢大佬吧😆

**Comment by sophisticate9008** [comment]
> 大大之后有计划多人下注不，感觉应该会很欢乐吧🤣

暂时写好了一个多人功能

**Comment by 1294266616** [comment]
> > 大大之后有计划多人下注不，感觉应该会很欢乐吧🤣
> 
> 暂时写好了一个多人功能

🐂🍺好的试试看会不会出bug，光荣小白鼠好🥥

**Comment by sophisticate9008** [comment]
以后代码大功能更新的第一天就不能下，第二天才旁观者清，自己就想到好多bug

**Comment by 1294266616** [comment]
> 以后代码大功能更新的第一天就不能下，第二天才旁观者清，自己就想到好多bug

大佬应援会应援后能加上机器人at并回复已经应援的目标和金币，单人到没有这个问题很快响应多人因为60秒等待发过去都不知道有没有收到命令

**Comment by sophisticate9008** [comment]
只要在六十秒内发，不回复默认就是成功，到时候加个六十秒后出应援单子，在结算的前面就好了

**Comment by sophisticate9008** [comment]
> > 以后代码大功能更新的第一天就不能下，第二天才旁观者清，自己就想到好多bug
> 
> 大佬应援会应援后能加上机器人at并回复已经应援的目标和金币，单人到没有这个问题很快响应多人因为60秒等待发过去都不知道有没有收到命令

![image](https://user-images.githubusercontent.com/94435821/183290885-2b99a9ad-4ec5-4b2c-99bb-b889de816944.png)
